const portfolioData = [
  {
    id: 1,
    clientName: "Profit Assurance",
    category: "Website Design",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/pat-thumb.jpg",
    bannerImage: "/pat-thumb.jpg",
    bannerTitle: "Design That Speaks the Brand’s Language",
    bannerDesc: "We built a fast and attractive website for Profit Assurance that improves speed, clarity, and user experience, while matching their brand and goals.",
    introDescription:
      "We don’t just design websites — we build digital experiences that turn visitors into loyal customers. Every project is powered by passion, clarity, and innovation, built to boost your brand and your bottom line. At Expresso Digital, we don’t just build websites — we craft experiences that blend aesthetics, functionality, and results. Every project in our portfolio is a reflection of our commitment to innovation, simplicity, and client success.",
    problems:
      "The previous website lacked optimal performance and did not align with the brand’s evolving identity. There was a need to enhance loading speed, improve layout scalability across devices, and create a more interactive and informative user experience. Additionally, branding consistency and visual hierarchy required refinement to make the site more engaging and conversion-driven.",
    solutions: [
      "Built with React for fast and dynamic performance.",
      "Reusable components for consistency and scalability.",
      "Optimized images: high quality with smaller size.",
      "Lazy loading and code splitting for faster load.",
      "Mobile-first responsive layout.",
      "SEO-friendly structure and smooth UX.",
    ],
    solutionImage: "/pat-gallery1.png",
    result:
      "The client was extremely pleased with the final outcome, as the website reflected their vision with precision. By closely understanding and executing the client’s intentions, we delivered a solution that not only aligned with their brand goals but also enhanced user engagement. The improved structure, visual appeal, and functionality exceeded expectations, resulting in increased satisfaction, better usability, and positive feedback from their audience.",
    imageUrls: [
      {
        src: "/pat5.png",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/pat6.png",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/pat7.png",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/pat-gallery1.png",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/pat-gallery2.jpeg",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/pat8.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  {
    id: 2,
    clientName: "Odeur Perfumes",
    category: "Website Design",
    bannerTitle: "Tailored E-Commerce Built for a Lasting Impression",
    bannerDesc: "We built a sleek and high-performing e-commerce platform for Odeur Perfumes, with fast loading times, advanced customization, and smooth user journeys that align perfectly with the brand's premium identity.",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    bannerImage: "/odeur.jpg",
    thumbnailImg: "/odeur.jpg",
    introDescription: "At Odeur Perfumes, our mission was to design more than just an online store — we created a fully customized e-commerce experience that combines elegance, functionality, and speed. From product display to seamless checkout, every detail reflects our dedication to quality, creativity, and performance.",
    problems: "The previous site lacked performance, flexibility, and ease of management. The client needed a fast-loading, scalable e-commerce platform with easy product upload, real-time analytics, and the ability to customize layouts. A streamlined admin dashboard and smoother shopping experience were also top priorities.",
    solutions: [
      "Built with React for speed and interactivity.",
      "Tailwind CSS for responsive, modern design.",
      "MongoDB and Node.js for scalable backend support.",
      "Redux for efficient global state management.",
      "Optimized images and lazy loading for fast performance.",
      // "Secure and flexible structure for future growth.",
    ],
    solutionImage: "/odeur1.jpeg",
    result: "The client was thrilled with the outcome — the website loaded faster, was easier to manage, and offered a sleek, user-friendly experience. With better performance and smooth navigation, customer engagement increased, and the brand saw a noticeable boost in online sales shortly after launch.",
    imageUrls: [
      {
        src: "/odeur1.jpeg",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/odeur2.jpeg",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/odeur3.jpeg",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/odeur4.jpeg",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/odeur-cart.png",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/odeur-create.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  // {
  //   id: 3,
  //   clientName: "Al Safi",
  //   bannerTitle: "Modernizing Al Safi’s Digital Showcase",
  //   category: "Website Design",
  //   bannerDesc: "We transformed Al Safi’s outdated website into a sleek, responsive platform with product management, performance upgrades, and a fresh visual identity — built with React and Node.js.",
  //   startDate: "10 March 2023",
  //   endDate: "30 March 2023",
  //   thumbnailImg: "/godfel.jpeg",
  //   introDescription: "Al Safi, a brand known for quality kitchen utensils, needed a complete website overhaul. Their previous site was outdated, non-responsive, and hard to manage. We stepped in to build a fast, modern, and easy-to-manage digital platform that reflects their brand quality and product range.",
  //   problems: "Al Safi’s old website was outdated, unresponsive on mobile, and visually unappealing. It lacked a product management system, making updates time-consuming. The overall user experience didn’t reflect the brand’s professionalism or product quality.",
  //   solutions: [
  //     "Built with React for a fast, responsive UI.",
  //     "Custom admin dashboard for easy product uploads.",
  //     "Node.js and MongoDB for a scalable backend.",
  //     "Modern, product-focused layout design.",
  //     "Fully responsive across all devices.",
  //     "Simplified navigation for better UX.",
  //   ],    
  //   solutionImage: "/pat-gallery1.png",
  //   result: "The new website gave Al Safi a fresh, modern look with smooth functionality. The client was happy with how easy it is to manage products through the dashboard. With improved performance and design, user engagement increased and the brand’s online presence was strengthened.",
  //   imageUrls: [
  //     {
  //       src: "/web-banner.jpg",
  //       alt: "Solution Image 1",
  //       rotate: "6deg",
  //       top: "20%",
  //       left: "25%",
  //       className: "w-36 md:w-56",
  //     },
  //     {
  //       src: "/web-banner.jpg",
  //       alt: "Solution Image 2",
  //       rotate: "12deg",
  //       top: "45%",
  //       left: "60%",
  //       className: "w-24 md:w-56",
  //     },
  //     {
  //       src: "/web-banner.jpg",
  //       alt: "Solution Image 3",
  //       rotate: "-6deg",
  //       top: "20%",
  //       left: "40%",
  //       className: "w-52 md:w-56",
  //     },
  //     {
  //       src: "/pat-gallery1.png",
  //       alt: "Mobile App Image 1",
  //       rotate: "8deg",
  //       top: "25%",
  //       left: "35%",
  //       className: "w-36 md:w-72",
  //     },
  //     {
  //       src: "/pat-gallery2.jpeg",
  //       alt: "Mobile App Image 2",
  //       rotate: "10deg",
  //       top: "30%",
  //       left: "40%",
  //       className: "w-40 md:w-60",
  //     },
  //     {
  //       src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //       alt: "Mobile App Image 3",
  //       rotate: "-8deg",
  //       top: "15%",
  //       left: "50%",
  //       className: "w-48 md:w-64",
  //     },
  //   ],
  // },
  {
    id: 4,
    clientName: "Godfel Group",
    category: "Website Design",
    bannerTitle: "From Scratch to Strategy — A Website That Works",
    bannerDesc: "We upgraded Godfel Group’s static website into a polished, responsive, and SEO-optimized platform — ensuring better performance, visibility, and brand consistency.",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/godfel.jpeg",
    bannerImage: "/godfel.jpeg",
    introDescription: "Godfel Group operates across industries — from HR consultancy to logistics — and needed a website that reflected their scale and professionalism. Their previous site was slow, outdated, and not optimized for mobile or search visibility. Our goal was to create a modern, responsive, and manageable WordPress site tailored to their growing business.",
    problems: "Al Safi’s old website was outdated, unresponsive on mobile, and visually unappealing. It lacked a product management system, making updates time-consuming. The overall user experience didn’t reflect the brand’s professionalism or product quality.",
    solutions: [
      "Built for seamless scalability as your business grows.",
      "Optimized for speed and performance.",
      "Modern, product-focused layout design.",
      "Fully responsive across all devices.",
      "Simplified navigation for better UX.",
    ],    
    solutionImage: "/godfel1.png",
    result: "The new website gave Al Safi a fresh, modern look with smooth functionality. The client was happy with how easy it is to manage products through the dashboard. With improved performance and design, user engagement increased and the brand’s online presence was strengthened.",
    imageUrls: [
      {
        src: "/godfel1.png",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/godfel2.png",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/godfel3.png",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/godfel4.png",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/godfel-logo.png",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/godfel5.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  {
    id: 5,
    clientName: "Ulitimate Mena",
    category: "Social Media",
    bannerTitle: "Fueling a Digital Voice for Ultimate MENA",
    bannerDesc: "From zero to traction — we crafted a bold social presence for Ultimate MENA that drives attention, builds trust, and reflects their industry edge.",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/ultimate.png",
    bannerImage: "/ultimate.png",
    problems: "Ultimate MENA had little to no social presence. Their identity was scattered, content was inconsistent, and they lacked a strategy to speak to the right audience. There were no performance metrics, creative direction, or content calendar in place — making it hard to grow or track engagement.",
    introDescription: "Ultimate MENA, a growing name in the lubricant oil industry, wanted to shift gears digitally. With no active social presence and a brand that felt invisible online, we were tasked with building awareness from the ground up — with clarity, consistency, and performance-led content.",
    solutions: [
      "Established a clear, B2B-focused visual identity.",
      "Planned and scheduled monthly content with strategy.",
      "Designed engaging posts, reels, and stories.",
      "Enabled analytics to track reach and engagement.",
      "Maintained brand consistency across platforms.",
    ],
    solutionImage: "/ulti7.png",
    result: "In just weeks, Ultimate MENA's digital visibility improved across platforms. With consistent content, clear messaging, and measurable performance, they began receiving more inquiries and building credibility in a highly competitive space. The brand now speaks with clarity — and the audience listens.",
    imageUrls: [
      {
        src: "/ulti1.png",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/ulti2.png",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/ulti4.png",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/ulti6.png",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/ulti4.png",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/ulti3.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  {
    id: 6,
    clientName: "Odeur Perfumes",
    category: "Social Media",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/odeur.png",
    bannerImage: "/odeur.png",
    bannerTitle: "Giving Odeur a Digital Pulse Beyond the Bottle",
    bannerDesc: "We turned Odeur’s offline luxury into online influence — curating content, building visibility, and crafting a voice that connects with fragrance lovers across platforms.",
    introDescription: "Odeur Perfumes needed more than just product visuals — they needed presence. We built a social strategy from the ground up, focusing on brand consistency, storytelling, and engagement. From bottle shots to branding reels, everything reflected the elegance of their products and the ambition of their voice.",
    problems: "Despite their strong product quality, Odeur had no active or consistent presence on social media. The brand lacked direction, content planning, and visibility. There were no clear engagement metrics, and posting was irregular — leaving potential reach untapped.",
    solutions: [
      "Created a bold visual identity for social platforms.",
      "Designed branded visuals and storytelling creatives.",
      "Wrote captions tailored for Instagram and LinkedIn.",
      "Used hashtags and timing to boost reach.",
      "Tracked performance and refined strategy.",
    ],
    solutionImage: "/odeur1.jpeg",
    result: "Odeur’s digital following started growing steadily within the first month. The consistent, elevated visuals helped strengthen brand recall, while regular engagement led to more DMs, product inquiries, and shares. The client now has a structured, stylish presence — and a community that’s paying attention.",
    imageUrls: [
      {
        src: "/odu1.png",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/odu2.png",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/odu6.png",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/odu3.png",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/odu4.png",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/odu5.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  {
    id: 7,
    clientName: "Baytwaard",
    category: "Social Media",
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/baytward.png",
    bannerImage: "/baytward.png",
    bannerTitle: "Serving Baytwaard’s Flavors on Social",
    bannerDesc: "We helped Baytwaard turn their kitchen vibes into scroll-stopping content — crafting a social media presence that’s as inviting as their menu.",
    introDescription: "Baytwaard is more than a restaurant — it’s an experience. But online, their flavor was missing. We stepped in to capture their dishes, mood, and brand story with a content strategy that speaks to food lovers and drives real engagement.",
    problems: "Baytwaard had an inconsistent feed, no content plan, and visuals that didn’t do justice to the quality of their food. Without clear branding or engagement tracking, the restaurant wasn’t making an impression online — or attracting new customers through social channels.",
    solutions: [
      "Created a consistent, appetizing visual style.",
      "Designed high-quality food and ambiance posts.",
      "Planned monthly content with offers and highlights.",
      "Wrote engaging, community-driven captions.",
      "Optimized hashtags, timing, and tracked results.",
    ],
    solutionImage: "/baytu7.png",
    result: "Baytwaard's Instagram and Facebook feeds now reflect their real-life charm — from sizzling grill shots to cozy dine-in vibes. With consistent content and improved engagement, the restaurant gained visibility, loyal followers, and more footfall from social referrals.",
    imageUrls: [
      {
        src: "/baytu1.png",
        alt: "Solution Image 1",
        rotate: "6deg",
        top: "20%",
        left: "25%",
        className: "w-36 md:w-56",
      },
      {
        src: "/baytu2.png",
        alt: "Solution Image 2",
        rotate: "12deg",
        top: "45%",
        left: "60%",
        className: "w-24 md:w-56",
      },
      {
        src: "/baytu6.png",
        alt: "Solution Image 3",
        rotate: "-6deg",
        top: "20%",
        left: "40%",
        className: "w-52 md:w-56",
      },
      {
        src: "/baytu3.png",
        alt: "Mobile App Image 1",
        rotate: "8deg",
        top: "25%",
        left: "35%",
        className: "w-36 md:w-72",
      },
      {
        src: "/baytu4.png",
        alt: "Mobile App Image 2",
        rotate: "10deg",
        top: "30%",
        left: "40%",
        className: "w-40 md:w-60",
      },
      {
        src: "/baytu5.png",
        alt: "Mobile App Image 3",
        rotate: "-8deg",
        top: "15%",
        left: "50%",
        className: "w-48 md:w-64",
      },
    ],
  },
  //   {
  //     id: 7,
  //     clientName: "Angelic Aroma Perfumes",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 8,
  //     clientName: "Alpha Dental Center",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 9,
  //     clientName: "MIH Dental Clinic",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 10,
  //     clientName: "Floraison Dental Clinic",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 11,
  //     clientName: "Bayt Ward",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 12,
  //     clientName: "Kottakkal Ayur Health",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 13,
  //     clientName: "Rahat Rent a Car",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 14,
  //     clientName: "Smile Essential Dental clinic",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 15,
  //     clientName: "Profit Assurance",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
  //   {
  //     id: 16,
  //     clientName: "Profit Assurance",
  //     category: "Website Design",
  //     startDate: "10 March 2023",
  //     endDate: "30 March 2023",
  //     thumbnailImg: "/web-banner.jpg",
  //     introDescription:
  //       "We show only the best websites and portfolios built completely with passion, simplicity, and creativity. Our team has designed game-changing products, constructed for companies as well. Each project reflects our commitment to excellence and innovation.",
  //     problems:
  //       "Outdated website design that lacked modern aesthetics and usability. No proper analytics or user dashboard for tracking website performance. Limited control over website updates and content.",
  //     solutions: [
  //       "Full business control/business control.",
  //       "User dashboard & analytics business control.",
  //       "Regular update monitoring business control.",
  //       "Curabitur fringilla turpis sed business control.",
  //       "Morbi rutrum ullam corper business control.",
  //       "Suscipit pharetra mauris business control.",
  //     ],
  //     solutionImages: ["/web-banner.jpg", "/web-banner.jpg"],
  //     result:
  //       "The revamped website improved user engagement, streamlined content updates, and provided actionable insights through an integrated analytics dashboard. The client saw a significant improvement in customer satisfaction and overall website performance.",
  //     imageUrls: [
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 1",
  //         rotate: "6deg",
  //         top: "20%",
  //         left: "25%",
  //         className: "w-36 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 2",
  //         rotate: "12deg",
  //         top: "45%",
  //         left: "60%",
  //         className: "w-24 md:w-56",
  //       },
  //       {
  //         src: "/web-banner.jpg",
  //         alt: "Solution Image 3",
  //         rotate: "-6deg",
  //         top: "20%",
  //         left: "40%",
  //         className: "w-52 md:w-56",
  //       },
  //       {
  //         src: "/pat-gallery1.png",
  //         alt: "Mobile App Image 1",
  //         rotate: "8deg",
  //         top: "25%",
  //         left: "35%",
  //         className: "w-36 md:w-72",
  //       },
  //       {
  //         src: "/pat-gallery2.jpeg",
  //         alt: "Mobile App Image 2",
  //         rotate: "10deg",
  //         top: "30%",
  //         left: "40%",
  //         className: "w-40 md:w-60",
  //       },
  //       {
  //         src: "https://images.unsplash.com/photo-1635373670332-43ea883bb081?q=80&w=2781&auto=format&fit=crop",
  //         alt: "Mobile App Image 3",
  //         rotate: "-8deg",
  //         top: "15%",
  //         left: "50%",
  //         className: "w-48 md:w-64",
  //       },
  //     ],
  //   },
];

export default portfolioData;
