import "dotenv/config";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import Portfolio from "../modules/portfolio/portfolio.model.js";

const ITEMS = [
  {
    slug: "profit-assurance",
    title: "Profit Assurance",
    clientName: "Profit Assurance",
    category: "Website Design",
    status: "published",
    sortOrder: 1,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/pat-thumb.jpg",
    bannerImage: "/pat-thumb.jpg",
    bannerTitle: "Design That Speaks the Brand's Language",
    bannerDesc: "We built a fast and attractive website for Profit Assurance that improves speed, clarity, and user experience, while matching their brand and goals.",
    excerpt: "We built a fast and attractive website for Profit Assurance that improves speed, clarity, and user experience.",
    introDescription: "We don't just design websites — we build digital experiences that turn visitors into loyal customers. Every project is powered by passion, clarity, and innovation, built to boost your brand and your bottom line. At Expresso Digital, we don't just build websites — we craft experiences that blend aesthetics, functionality, and results. Every project in our portfolio is a reflection of our commitment to innovation, simplicity, and client success.",
    problems: "The previous website lacked optimal performance and did not align with the brand's evolving identity. There was a need to enhance loading speed, improve layout scalability across devices, and create a more interactive and informative user experience. Additionally, branding consistency and visual hierarchy required refinement to make the site more engaging and conversion-driven.",
    solutions: [
      "Built with React for fast and dynamic performance.",
      "Reusable components for consistency and scalability.",
      "Optimized images: high quality with smaller size.",
      "Lazy loading and code splitting for faster load.",
      "Mobile-first responsive layout.",
      "SEO-friendly structure and smooth UX.",
    ],
    solutionImage: "/pat-gallery1.png",
    result: "The client was extremely pleased with the final outcome, as the website reflected their vision with precision. By closely understanding and executing the client's intentions, we delivered a solution that not only aligned with their brand goals but also enhanced user engagement. The improved structure, visual appeal, and functionality exceeded expectations, resulting in increased satisfaction, better usability, and positive feedback from their audience.",
    imageUrls: [
      { src: "/pat5.png", alt: "Solution Image 1" },
      { src: "/pat6.png", alt: "Solution Image 2" },
      { src: "/pat7.png", alt: "Solution Image 3" },
      { src: "/pat-gallery1.png", alt: "Mobile App Image 1" },
      { src: "/pat-gallery2.jpeg", alt: "Mobile App Image 2" },
      { src: "/pat8.png", alt: "Mobile App Image 3" },
    ],
  },
  {
    slug: "odeur-perfumes-website",
    title: "Odeur Perfumes — Website",
    clientName: "Odeur Perfumes",
    category: "Website Design",
    status: "published",
    sortOrder: 2,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/odeur.jpg",
    bannerImage: "/odeur.jpg",
    bannerTitle: "Tailored E-Commerce Built for a Lasting Impression",
    bannerDesc: "We built a sleek and high-performing e-commerce platform for Odeur Perfumes, with fast loading times, advanced customization, and smooth user journeys that align perfectly with the brand's premium identity.",
    excerpt: "Sleek and high-performing e-commerce platform for Odeur Perfumes.",
    introDescription: "At Odeur Perfumes, our mission was to design more than just an online store — we created a fully customized e-commerce experience that combines elegance, functionality, and speed. From product display to seamless checkout, every detail reflects our dedication to quality, creativity, and performance.",
    problems: "The previous site lacked performance, flexibility, and ease of management. The client needed a fast-loading, scalable e-commerce platform with easy product upload, real-time analytics, and the ability to customize layouts. A streamlined admin dashboard and smoother shopping experience were also top priorities.",
    solutions: [
      "Built with React for speed and interactivity.",
      "Tailwind CSS for responsive, modern design.",
      "MongoDB and Node.js for scalable backend support.",
      "Redux for efficient global state management.",
      "Optimized images and lazy loading for fast performance.",
    ],
    solutionImage: "/odeur1.jpeg",
    result: "The client was thrilled with the outcome — the website loaded faster, was easier to manage, and offered a sleek, user-friendly experience. With better performance and smooth navigation, customer engagement increased, and the brand saw a noticeable boost in online sales shortly after launch.",
    imageUrls: [
      { src: "/odeur1.jpeg", alt: "Solution Image 1" },
      { src: "/odeur2.jpeg", alt: "Solution Image 2" },
      { src: "/odeur3.jpeg", alt: "Solution Image 3" },
      { src: "/odeur4.jpeg", alt: "Mobile App Image 1" },
      { src: "/odeur-cart.png", alt: "Mobile App Image 2" },
      { src: "/odeur-create.png", alt: "Mobile App Image 3" },
    ],
  },
  {
    slug: "godfel-group",
    title: "Godfel Group",
    clientName: "Godfel Group",
    category: "Website Design",
    status: "published",
    sortOrder: 3,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/godfel.jpeg",
    bannerImage: "/godfel.jpeg",
    bannerTitle: "From Scratch to Strategy — A Website That Works",
    bannerDesc: "We upgraded Godfel Group's static website into a polished, responsive, and SEO-optimized platform — ensuring better performance, visibility, and brand consistency.",
    excerpt: "We upgraded Godfel Group's static website into a polished, responsive, and SEO-optimized platform.",
    introDescription: "Godfel Group operates across industries — from HR consultancy to logistics — and needed a website that reflected their scale and professionalism. Their previous site was slow, outdated, and not optimized for mobile or search visibility. Our goal was to create a modern, responsive, and manageable WordPress site tailored to their growing business.",
    problems: "Godfel Group's old website was outdated, unresponsive on mobile, and visually unappealing. It lacked a product management system, making updates time-consuming. The overall user experience didn't reflect the brand's professionalism or product quality.",
    solutions: [
      "Built for seamless scalability as your business grows.",
      "Optimized for speed and performance.",
      "Modern, product-focused layout design.",
      "Fully responsive across all devices.",
      "Simplified navigation for better UX.",
    ],
    solutionImage: "/godfel1.png",
    result: "The new website gave Godfel Group a fresh, modern look with smooth functionality. The client was happy with how easy it is to manage content through the dashboard. With improved performance and design, user engagement increased and the brand's online presence was strengthened.",
    imageUrls: [
      { src: "/godfel1.png", alt: "Solution Image 1" },
      { src: "/godfel2.png", alt: "Solution Image 2" },
      { src: "/godfel3.png", alt: "Solution Image 3" },
      { src: "/godfel4.png", alt: "Mobile App Image 1" },
      { src: "/godfel-logo.png", alt: "Mobile App Image 2" },
      { src: "/godfel5.png", alt: "Mobile App Image 3" },
    ],
  },
  {
    slug: "ultimate-mena",
    title: "Ultimate MENA",
    clientName: "Ulitimate Mena",
    category: "Social Media",
    status: "published",
    sortOrder: 4,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/ultimate.png",
    bannerImage: "/ultimate.png",
    bannerTitle: "Fueling a Digital Voice for Ultimate MENA",
    bannerDesc: "From zero to traction — we crafted a bold social presence for Ultimate MENA that drives attention, builds trust, and reflects their industry edge.",
    excerpt: "From zero to traction — bold social presence for Ultimate MENA.",
    introDescription: "Ultimate MENA, a growing name in the lubricant oil industry, wanted to shift gears digitally. With no active social presence and a brand that felt invisible online, we were tasked with building awareness from the ground up — with clarity, consistency, and performance-led content.",
    problems: "Ultimate MENA had little to no social presence. Their identity was scattered, content was inconsistent, and they lacked a strategy to speak to the right audience. There were no performance metrics, creative direction, or content calendar in place — making it hard to grow or track engagement.",
    solutions: [
      "Established a clear, B2B-focused visual identity.",
      "Planned and scheduled monthly content with strategy.",
      "Designed engaging posts, reels, and stories.",
      "Enabled analytics to track reach and engagement.",
      "Maintained brand consistency across platforms.",
    ],
    solutionImage: "/ulti7.png",
    result: "In just weeks, Ultimate MENA's digital visibility improved across platforms. With consistent content, clear messaging, and measurable performance, they began receiving more inquiries and building credibility in a highly competitive space. The brand now speaks with clarity — and the audience listens.",
    imageUrls: [
      { src: "/ulti1.png", alt: "Solution Image 1" },
      { src: "/ulti2.png", alt: "Solution Image 2" },
      { src: "/ulti4.png", alt: "Solution Image 3" },
      { src: "/ulti6.png", alt: "Mobile App Image 1" },
      { src: "/ulti4.png", alt: "Mobile App Image 2" },
      { src: "/ulti3.png", alt: "Mobile App Image 3" },
    ],
  },
  {
    slug: "odeur-perfumes-social",
    title: "Odeur Perfumes — Social Media",
    clientName: "Odeur Perfumes",
    category: "Social Media",
    status: "published",
    sortOrder: 5,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/odeur.png",
    bannerImage: "/odeur.png",
    bannerTitle: "Giving Odeur a Digital Pulse Beyond the Bottle",
    bannerDesc: "We turned Odeur's offline luxury into online influence — curating content, building visibility, and crafting a voice that connects with fragrance lovers across platforms.",
    excerpt: "We turned Odeur's offline luxury into online influence.",
    introDescription: "Odeur Perfumes needed more than just product visuals — they needed presence. We built a social strategy from the ground up, focusing on brand consistency, storytelling, and engagement. From bottle shots to branding reels, everything reflected the elegance of their products and the ambition of their voice.",
    problems: "Despite their strong product quality, Odeur had no active or consistent presence on social media. The brand lacked direction, content planning, and visibility. There were no clear engagement metrics, and posting was irregular — leaving potential reach untapped.",
    solutions: [
      "Created a bold visual identity for social platforms.",
      "Designed branded visuals and storytelling creatives.",
      "Wrote captions tailored for Instagram and LinkedIn.",
      "Used hashtags and timing to boost reach.",
      "Tracked performance and refined strategy.",
    ],
    solutionImage: "/odeur1.jpeg",
    result: "Odeur's digital following started growing steadily within the first month. The consistent, elevated visuals helped strengthen brand recall, while regular engagement led to more DMs, product inquiries, and shares. The client now has a structured, stylish presence — and a community that's paying attention.",
    imageUrls: [
      { src: "/odu1.png", alt: "Solution Image 1" },
      { src: "/odu2.png", alt: "Solution Image 2" },
      { src: "/odu6.png", alt: "Solution Image 3" },
      { src: "/odu3.png", alt: "Mobile App Image 1" },
      { src: "/odu4.png", alt: "Mobile App Image 2" },
      { src: "/odu5.png", alt: "Mobile App Image 3" },
    ],
  },
  {
    slug: "baytwaard",
    title: "Baytwaard",
    clientName: "Baytwaard",
    category: "Social Media",
    status: "published",
    sortOrder: 6,
    startDate: "10 March 2023",
    endDate: "30 March 2023",
    thumbnailImg: "/baytward.png",
    bannerImage: "/baytward.png",
    bannerTitle: "Serving Baytwaard's Flavors on Social",
    bannerDesc: "We helped Baytwaard turn their kitchen vibes into scroll-stopping content — crafting a social media presence that's as inviting as their menu.",
    excerpt: "Scroll-stopping social content for Baytwaard restaurant.",
    introDescription: "Baytwaard is more than a restaurant — it's an experience. But online, their flavor was missing. We stepped in to capture their dishes, mood, and brand story with a content strategy that speaks to food lovers and drives real engagement.",
    problems: "Baytwaard had an inconsistent feed, no content plan, and visuals that didn't do justice to the quality of their food. Without clear branding or engagement tracking, the restaurant wasn't making an impression online — or attracting new customers through social channels.",
    solutions: [
      "Created a consistent, appetizing visual style.",
      "Designed high-quality food and ambiance posts.",
      "Planned monthly content with offers and highlights.",
      "Wrote engaging, community-driven captions.",
      "Optimized hashtags, timing, and tracked results.",
    ],
    solutionImage: "/baytu7.png",
    result: "Baytwaard's Instagram and Facebook feeds now reflect their real-life charm — from sizzling grill shots to cozy dine-in vibes. With consistent content and improved engagement, the restaurant gained visibility, loyal followers, and more footfall from social referrals.",
    imageUrls: [
      { src: "/baytu1.png", alt: "Solution Image 1" },
      { src: "/baytu2.png", alt: "Solution Image 2" },
      { src: "/baytu6.png", alt: "Solution Image 3" },
      { src: "/baytu3.png", alt: "Mobile App Image 1" },
      { src: "/baytu4.png", alt: "Mobile App Image 2" },
      { src: "/baytu5.png", alt: "Mobile App Image 3" },
    ],
  },
];

async function run() {
  await connectDB();

  for (const item of ITEMS) {
    await Portfolio.findOneAndUpdate(
      { slug: item.slug },
      { ...item, publishedAt: new Date() },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`✅ Seeded: ${item.clientName} (${item.category})`);
  }

  await mongoose.connection.close();
  console.log("✅ Portfolio seed complete");
}

run().catch((err) => {
  console.error("❌ seedPortfolio failed:", err);
  process.exit(1);
});
